name: cory's pipeline
on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "rafal-moe-repo-private",
                "username": "${{ secrets.RAFAL_MOE_REPO_IDENTITY }}",
                "password": "${{ secrets.RAFAL_MOE_REPO_TOKEN }}"
            }]
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v4.0.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
